default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: mac
  password:

development:
  <<: *default
  database: subrother_development

test:
  <<: *default
  database: subrother_testing
